server:
  port: 8064
spring:
  application:
    name: microsv-a
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&connectTimeout=10000&socketTimeout=300000&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr} #指定注册中心地址
        username: nacos
        password: nacos
      server-addr: localhost:8850 #指R定nacos服务地址 使用nginx进行负载均衡
#      server-addr: localhost:8848,localhost:8845,localhost:8842 #指定nacos服务地址
#  config:
#    import:
#      - optional:nacos:microsv-a
#      - optional:nacos:provider-config-dev.yml  # 监听 PROVIDER_GROUP :provider-config-dev.yml
#      - optional:nacos:provider-config-dev.yml?group=group_01  # 覆盖默认 group，监听 group_01:provider-config-dev.yml
#      - optional:nacos:provider-config-dev.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
    sentinel:
      eager: true
      enabled: true
      transport:
        port: 8719
        #sentinel服务器地址和端口
        dashboard: 127.0.0.1:8070
        #当前项目地址，如果sentinel服务器地址和项目地址一致可不填写
        client-ip: 127.0.0.1
logging:
  config: classpath:log4j2.xml